const COURSES = [
  {
    img: "/image/blogs/blog4.svg",
    tag: "Prof. Srishti Dey • Mr. Subhasis Chakraborty",
    title: "Fundamentals of Industrial IoT (IIoT)",
    label: "INR 5,000",
    desc: "Offered by: Department of CSE (AI & ML) in association with Cryptappz Technologies LLP",
    days: "Days: Friday, Saturday(Proposed)",
    time: "Time: 11 am - 1 pm",
    mode: "Mode of Conduction: Online",
    seat: "Seats: 30",
    duration: "Duration: 1 month (Contact Hours: 36 Hrs)",
  },
  {
    img: "/image/blogs/blog4.svg",
    tag: "Mr. Shehasis Banerjee • Prof. (Dr.) Ramen Pal",
    title: "Reinforcement & Deep Learning using Python",
    label: "INR 5,000",
    desc: "Offered by: Department of CSE (AI & ML)",
    days: "Days: Saturday, Sunday (Proposed)",
    time: "Time: 11 am - 1 pm",
    mode: "Mode of Conduction: Online",
    seat: "Seats: 30",
    duration: "Duration: 1 month (Contact Hours: 24Hrs)",
  },
  {
    img: "/image/blogs/blog4.svg",
    tag: "Dr. Arnab Paul • Mr. Deepjyoti Roy • Prof. (Dr.) Ramen Pal",
    title: "AI-based Recommendation System",
    label: "INR 5,000",
    desc: "Offered by: Department of CSE (AI & ML)",
    days: "Days: Monday, Tuesday, Wednesday (Proposed)",
    time: "Time: 11 am - 1 pm",
    mode: "Mode of Conduction: Online",
    seat: "Seats: 30",
    duration: "Duration: 1 month (Contact Hours: 24Hrs)",
  },
  {
    img: "/image/blogs/blog4.svg",
    tag: "Prof. Srishti Dey • Mr. Ajay Krishna N A",
    title: "Fundamental on Computer Forensics",
    label: "INR 5,000",
    desc: "Offered by: Department of CSE (AI & ML) in association with IEM Labs",
    days: "Days: Friday, Saturday, Sunday (Proposed)",
    time: "Time: 11 am - 1 pm",
    mode: "Mode of Conduction: Online",
    seat: "Seats: 30",
    duration: "Duration: 1 month (Contact Hours: 24 Hrs)",
  },
  {
    img: "/image/blogs/blog4.svg",
    tag: "Prof. Anirban Ganguly • Mrs. Pooja Joshi",
    title:
      "Hands-on with InMemory Computing (IMC): A hardware level perspective",
    label: "INR 5,000",
    desc: "Offered by: Department of CST & CSIT",
    days: "Days: Friday, Saturday(Proposed)",
    time: "Time: 11 am-1 pm & 2 pm-3 pm",
    mode: "Mode of Conduction: Hybrid/Online",
    seat: "Seats: 30",
    duration: "Duration: 1 month (Contact Hours: 24 Hrs)",
  },
];

export default COURSES;
